### ISSUE TITLE
コメントアウトがもう少しあると分かりやすいです。

### ISSUE THREAD

**Issue by c0a2113935** [C0A21145/ProjExD#12]
https://github.com/C0A21145/ProjExD/blob/26cf80ce7d27cff08b8c1fc9c8f5acbcecf48828/ex03/maze.py#L1

**Comment by c0a2113935** [comment]
コメントアウトがもう少しあると分かりやすいです。

**Comment by C0A21145** [comment]
コメントアウト増やしてわかりやすくしました！
