### ISSUE TITLE
見やすくて良いと思った

### ISSUE THREAD

**Issue by MinamiSawamura** [C0A21145/ProjExD#6]
https://github.com/C0A21145/ProjExD/blob/bebafd6b306ea28e2b168ced9dd901eb37d87486/ex02/calc.py#L8
#------での区切りや、長いfor文の分割があって、読みやすいコードになっていた。適切にコメントアウトがあるのも良い。

**Comment by C0A21145** [comment]
ありがとうございます。精進します。
