### ISSUE TITLE
ACを電卓の一番下の段だともっときれいになると思った。

### ISSUE THREAD

**Issue by c0a2113935** [C0A21145/ProjExD#7]
https://github.com/C0A21145/ProjExD/blob/92ef11c756e3767d1da4651e0295d951620d48f8/ex02/calc.py#L143

**Comment by C0A21145** [comment]
修正しました。
![image](https://user-images.githubusercontent.com/85730896/204488905-ca5a1392-ad2a-4987-9cda-f617a126530b.png)
