### ISSUE TITLE
記号が連続して入力できる

### ISSUE THREAD

**Issue by c0a2113791** [C0A21145/ProjExD#9]
https://github.com/C0A21145/ProjExD/blob/92ef11c756e3767d1da4651e0295d951620d48f8/ex02/calc.py#L127
「＝」が連続して入力できる。

**Comment by C0A21145** [comment]
`    elif txt == "=":
        if "=" in entry.get():
            pass
        else:
            entry.insert(tk.END, txt)`

以上のコードを追記することによって解決しました。
